- title: "圈友们"
  items:
    - name: "Kroxitine-克罗西丁"
      link: "https://kroxitine.com/"
      description: "如果让我多睡一会儿，我什么都愿意做的（辣鸡小伊）"
      avatar: "https://q1.qlogo.cn/g?b=qq&nk=2657124519&s=640"
    
    - name: "炎忍"
      link: "https://imyan.ren/"
      description: "热爱创造有趣的项目。"
      avatar: "https://q1.qlogo.cn/g?b=qq&nk=2323355219&s=640"
    
    - name: "扶摇 Skyrocketing"
      link: "https://fuyaoskyrocket.ing/"
      description: "尝试在互联网上留下一些属于自己的痕迹"
      avatar: "https://github.com/skyrocketingHong.png"
    
    - name: "Ctone"
      link: "https://onect.one/"
      description: "普普通通，勉勉强强算一名大学生（"
      avatar: "https://c.disquscdn.com/uploads/users/40625/5129/avatar92.jpg?1714050307"
    
    - name: "Mirage-米来吉"
      link: "https://miraged.fun/"
      description: ""
      avatar: "https://q1.qlogo.cn/g?b=qq&nk=669205145&s=640"

    - name: "橙橙忻冰乐"
      link: "https://blog.fraxxuccino.com/"
      description: "情之所钟，虽千万里吾念矣"
      avatar: "https://avatars.githubusercontent.com/u/224515785?v=4&size=64"

- title: "失联人士"
  items:
    - name: "Pi(品品)"
      link: "https://b.dopi.cc/"
      description: "这个人非常的懒，非常非常的懒"
      avatar: "https://q1.qlogo.cn/g?b=qq&nk=910083634&s=640"
      disable: true
    
    - name: "Wainbaro(肖究佟)"
      link: "https://wainbaro.github.io/"
      description: "\"画画使我快乐。\""
      avatar: "https://q1.qlogo.cn/g?b=qq&nk=1411878525&s=640"
      disable: true
    
    - name: "Gking(ZhanXiaoSong)"
      link: "https://www.gking.icu/"
      description: "自己来选择，不会后悔的道路"
      avatar: "https://www.gking.icu/img/avatar.png"
      disable: true
